## To customize Nu Designer configuration see https://docs.nussknacker.io/OSS_docs/configuration/Overview/

scenarioTypes {
  "streaming" {
    # customize Flink streaming scenario type
    # see: https://docs.nussknacker.io/OSS_docs/configuration/Overview/#configuration-file
  }
  "streaming-lite-embedded" {
    # customize Lite streaming scenario type
    # see: https://docs.nussknacker.io/OSS_docs/configuration/Overview/#configuration-file
  }
  "request-response-embedded": {
    # customize Lite request-response scenario type
    # see: https://docs.nussknacker.io/OSS_docs/configuration/Overview/#configuration-file
  }
}
