## To customize Nu Designer configuration see https://nussknacker.io/documentation/docs/configuration/Common

scenarioTypes {
  "streaming" {
    # customize Flink streaming scenario type
    # see: https://nussknacker.io/documentation/docs/configuration/Common/#configuration-file
    modelConfig {
#           components.worldTimeOpenAPI {
#             providerType: openAPI
#             url: "https://www.timeapi.io/swagger/v0.99.4/swagger.json"
#    #         url: "http://not_existing_url.pl/api"
#           }
           components.nuScenariosSQLComponent {
             providerType: databaseEnricher
             config: {
               databaseQueryEnricher {
                 name: "myDatabaseQuery"
                 dbPool: ${myDatabasePool} #refers to your database pool definition
               }
               databaseLookupEnricher {
                 name: "myDatabaseLookup"
                 dbPool: ${myDatabasePool}
               }
             }
           }
        }
  }
#  "streaming-lite-embedded" {
#    # customize Lite streaming scenario type
#    # see: https://nussknacker.io/documentation/docs/configuration/Common/#configuration-file
#  }
#  "request-response-embedded": {
#    # customize Lite request-response scenario type
#    # see: https://nussknacker.io/documentation/docs/configuration/Common/#configuration-file
#  }
}

myDatabasePool {
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/nu-db"
  username: "nu"
  password: "nupassword"
}
