ui:
- changed-files:
  - 'designer/client/*'
  - 'designer/client/**/*'
  - 'designer/submodules/*'
  - 'designer/submodules/**/*'

client:
- changed-files:
  - 'designer/client/*'
  - 'designer/client/**/*'

submodules:
- changed-files:
  - 'designer/submodules/*'
  - 'designer/submodules/**/*'

docs:
- changed-files:
  - '**/*.md'
  - 'docs/*'
  - 'docs/**/*'
