ui:
- changed-files:
  - any-glob-to-any-file:
    - 'designer/client/*'
    - 'designer/client/**/*'
    - 'designer/submodules/*'
    - 'designer/submodules/**/*'

client:
- changed-files:
  - any-glob-to-any-file:
    - 'designer/client/*'
    - 'designer/client/**/*'

submodules:
- changed-files:
  - any-glob-to-any-file:
    - 'designer/submodules/*'
    - 'designer/submodules/**/*'

docs:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'
    - 'docs/*'
    - 'docs/**/*'
