package pl.touk.nussknacker.ui.statistics

import pl.touk.nussknacker.engine.api.component.DefaultComponentName
import pl.touk.nussknacker.ui.statistics.ComponentKeys._

object ComponentMap {

  val componentMap: Map[String, StatisticKey] = Map(
    "aggregate"                                     -> Aggregate,
    DefaultComponentName.aggregateTumbling.toString -> AggregateTumbling,
    "componentService"                              -> ComponentService,
    "datesTypesService"                             -> DatesTypesService,
    "accountService"                                -> AccountService,
    "dynamicService"                                -> DynamicService,
    "optionalTypesService"                          -> OptionalTypesService,
    "monitor"                                       -> Monitor,
    "aggregate-sliding"                             -> AggregateSliding,
    "hideVariables"                                 -> HideVariables,
    "single-side-join"                              -> SingleSideJoin,
    "delay"                                         -> Delay,
    "request"                                       -> Request,
    "dead-end"                                      -> DeadEnd,
    "enricherNullResult"                            -> EnricherNullResult,
    "multipleParamsService"                         -> MultipleParamsService,
    "unionWithEditors"                              -> UnionWithEditors,
    "decision-table"                                -> DecisionTable,
    "real-kafka-json-SampleProduct"                 -> RealKafkaJsonSampleProduct,
    "union"                                         -> Union,
    "db-query"                                      -> DbQuery,
    "kafka-transaction"                             -> KafkaTransaction,
    "paramService"                                  -> ParamService,
    "real-kafka"                                    -> RealKafka,
    "modelConfigReader"                             -> ModelConfigReader,
    "oneSource"                                     -> OneSource,
    "constantStateTransformer"                      -> ConstantStateTransformer,
    "lastVariableWithFilter"                        -> LastVariableWithFilter,
    "stateful"                                      -> Stateful,
    "enrichWithAdditionalData"                      -> EnrichWithAdditionalData,
    "sendCommunication"                             -> SendCommunication,
    "clientHttpService"                             -> ClientHttpService,
    "full-outer-join"                               -> FullOuterJoin,
    "previousValue"                                 -> PreviousValue,
    "db-lookup"                                     -> DbLookup,
    "configuratorService"                           -> ConfiguratorService,
    "communicationSource"                           -> CommunicationSource,
    "listReturnObjectService"                       -> ListReturnObjectService,
    "filter"                                        -> Filter,
    "kafka"                                         -> Kafka,
    "response"                                      -> Response,
    "serviceModelService"                           -> ServiceModelService,
    "providedComponent-component-v1"                -> ProvidedComponentComponentV1,
    "simpleTypesCustomNode"                         -> SimpleTypesCustomNode,
    "dead-end-lite"                                 -> DeadEndLite,
    "collectionTypesService"                        -> CollectionTypesService,
    "unionReturnObjectService"                      -> UnionReturnObjectService,
    "campaignService"                               -> CampaignService,
    "providedComponent-component-v2"                -> ProvidedComponentComponentV2,
    "split"                                         -> Split,
    "classInstanceSource"                           -> ClassInstanceSource,
    "variable"                                      -> Variable,
    "boundedSource"                                 -> BoundedSource,
    "periodic"                                      -> Periodic,
    "additionalVariable"                            -> AdditionalVariable,
    "communicationSink"                             -> CommunicationSink,
    "echoEnumService"                               -> EchoEnumService,
    "choice"                                        -> Choice,
    "csv-source-lite"                               -> CsvSourceLite,
    "aggregate-session"                             -> AggregateSession,
    "csv-source"                                    -> CsvSource,
    "serviceWithDictParameterEditor"                -> ServiceWithDictParameterEditor,
    "collect"                                       -> Collect,
    "customValidatedService"                        -> CustomValidatedService,
    "complexReturnObjectService"                    -> ComplexReturnObjectService,
    "providedComponent-component-v3"                -> ProvidedComponentComponentV3,
    "kafka-string"                                  -> KafkaString,
    "for-each"                                      -> ForEach,
    "enricher"                                      -> Enricher,
    "constantStateTransformerLongValue"             -> ConstantStateTransformerLongValue,
    "simpleTypesService"                            -> SimpleTypesService,
    "genericSourceWithCustomVariables"              -> GenericSourceWithCustomVariables,
    "sendSms"                                       -> SendSms,
    "union-memo"                                    -> UnionMemo,
    "customFilter"                                  -> CustomFilter,
    "sql-source"                                    -> SqlSource,
    "log"                                           -> Log,
    "record-variable"                               -> RecordVariable,
    "dynamicMultipleParamsService"                  -> DynamicMultipleParamsService,
    "noneReturnTypeTransformer"                     -> NoneReturnTypeTransformer,
    "table"                                         -> Table,
    "meetingService"                                -> MeetingService,
    "transactionService"                            -> TransactionService,
  )

}
