export const variables = {
    alert: {
        info: "#cccccc",
        infoColor: "#b3b3b3",
        warningIcon: "#FF9A4D",
        warning: "#FF9A4D",
        error: "#f25c6e",
        okColor: "#8fad60",
        success: "#64d864",
        text: "#333333",
    },
    focus: "#0058a9",
    error: "f25c6e",
    ok: "#8fad60",
    panelTitleTextColor: "#808080",
    panelHeaderBackground: "#3e3e3e",
    buttonSize: "72px",
    buttonTextColor: "#cccccc",
    buttonBkgColor: "#4d4d4d",
    buttonBkgHover: "#444444",
    focusColor: "#0058a9",
    errorColor: "#f25c6e",
    okColor: "#8fad60",
    buttonSmallSize: "48",
    panelBackground: "#4D4D4D",
    defaultTextColor: "#ccc",
    panelBkgColor: "#444444",
    historyItemBackground: "#8d8d8d",
    buttonBorderColor: "#666666",
    menuButtonBorderColor: "#666666",
    menuButtonActiveBKColor: "#5d5d5d",

    sidebarWidth: 290,
    toolbarsGap: 3,
    scrollThumbSize: 8,
    panelWidth: 290 + 8,
    rightPanelButtonFontSize: 11,
    button: {
        buttonSize: "72px",
        smallSize: "48px",
    },
};

const newVariables = {
    border: {
        borderRadiusBase: 0,
        borderRadiusLarge: 0,
        borderRadiusSmall: 0,
    },
    containerPadding: 25,
    menu: {
        menuBarHeight: 50,
    },
    button: {
        buttonSize: 72,
        smallSize: 48,
    },
    panel: {
        panelHeaderTextSize: 10,
        panelHeaderHeight: 26,
        panelHeaderFontSize: 12,
    },
    sidebarWidth: 290,
    toolbarsGap: 3,
    scrollThumbSize: 8,
    panelWidth: 290 + 8,
    rightPanelButtonFontSize: 11,
    modal: {
        modalHeaderHeight: 30,
        modalHeaderWidth: 86,
        modalFooterHeight: 51,
        modalMaxHeight: 700,
        modalMaxWidth: 800,
        modalContentMaxHeight: 700 - 30 - 51 - 9, ////don't know why -9, but without it modal with scrollbar has weird footer and its edges come outside of modal
    },
};
