name: Free disk space
description: Removes some unused runner components to have more free space e.g. for Docker builds
runs:
  using: "composite"
  steps:
    # https://github.com/actions/runner-images/issues/2875
    # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
    - name: Increase free disk space
      shell: bash
      run: |
        echo "Free space before file removals:"
        df -h /
        echo

        set -x
        # 780M
        time sudo rm -rf /usr/share/miniconda

        # 370M
        time sudo rm -rf /opt/google/chrome
        # 619M
        time sudo rm -rf /opt/microsoft/msedge
        # 278M
        time sudo rm -rf /usr/lib/firefox
        # 626M
        time sudo rm -rf /usr/local/share/chromium

        # 550M
        time sudo rm -rf /usr/share/az_*
        # 4.2G
        time sudo rm -rf /usr/share/dotnet
        # 178M
        time sudo rm -rf /opt/microsoft/powershell
        # 1.3G
        time sudo rm -rf /usr/local/share/powershell

        # 2.3G
        time sudo rm -rf /usr/share/swift

        # 9.9G
        time sudo rm -rf /usr/local/lib/android

        # 1.7G
        time sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL"
        # 1.1G
        time sudo rm -rf "$AGENT_TOOLSDIRECTORY/go"
        # 520M
        time sudo rm -rf "$AGENT_TOOLSDIRECTORY/PyPy"
        # 1.7G
        time sudo rm -rf "$AGENT_TOOLSDIRECTORY/Python"
        # 313M
        time sudo rm -rf "$AGENT_TOOLSDIRECTORY/Ruby"

        echo -e "\nFree space after file removals:"
        df -h /
