{
 "title": "Scenario",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "scenarioName",
    "query": "SHOW TAG VALUES FROM \"source_instantRate\" WITH KEY = \"scenario\""
   },
   {
    "name": "env",
    "query": "SHOW TAG VALUES FROM \"source_instantRate\" WITH KEY = \"env\""
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,3m, 10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Source throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeName]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"source_count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, nodeName, slot\n)\nGROUP BY time($__interval), scenario, nodeId, nodeName\n"
    }
   ]
  },
  {
   "title": "Events that passed whole scenario /s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeName]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"end_count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, nodeName, slot\n)\nGROUP BY time($__interval), scenario, nodeId, nodeName\n"
    }
   ]
  },
  {
   "title": "Rejected events /s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeName]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"dead_end_count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, nodeName, slot\n)\nGROUP BY time($__interval), scenario, nodeId, nodeName\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeName]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"error_instantRateByNode_count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, nodeName, slot\n)\nGROUP BY time($__interval), scenario, nodeId, nodeName\n"
    }
   ]
  },
  {
   "title": "Max lag among Kafka source partitions (events)",
   "type": "graph",
   "description": "IMPORTANT. \nThis metric does NOT show the overall lag on Kafka source; a largest lag among all the source partitions is shown.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_operator_name]] (slot [[tag_slot]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "operator_name" ], "type": "tag" },
      { "params": [ "slot" ], "type": "tag" }
     ],
     "measurement": "records-lag-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - minimum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeName]] (slot [[tag_slot]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "slot" ], "type": "tag" },
      { "params": [ "nodeId" ], "type": "tag" },
      { "params": [ "nodeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay_histogram",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - median",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeName]] (slot [[tag_slot]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "nodeId" ], "type": "tag" },
      { "params": [ "nodeName" ], "type": "tag" },
      { "params": [ "slot" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay_histogram",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - maximum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeName]] (slot [[tag_slot]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "slot" ], "type": "tag" },
      { "params": [ "nodeId" ], "type": "tag" },
      { "params": [ "nodeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay_histogram",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time from latest event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeName]] (slot [[tag_slot]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "nodeId" ], "type": "tag" },
      { "params": [ "nodeName" ], "type": "tag" },
      { "params": [ "slot" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay_minimalDelay",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "External services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services - median OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]] (slot [[tag_slot]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "scenario" ], "type": "tag" },
        { "params": [ "serviceName" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "service_OK_histogram",
       "select": [
        [
         { "params": [ "p50" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Services - 99th percentile OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]] (slot [[tag_slot]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "scenario" ], "type": "tag" },
        { "params": [ "serviceName" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "service_OK_histogram",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Services - throughput OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]]",
       "query": "SELECT sum(mean)\nFROM (\n  SELECT mean(value)\n  FROM \"service_OK_instantRate\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, serviceName, slot\n)\nGROUP BY time($__interval), scenario, serviceName"
      }
     ]
    },
    {
     "title": "Services - median FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]] (slot [[tag_slot]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "scenario" ], "type": "tag" },
        { "params": [ "serviceName" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "service_FAIL_histogram",
       "select": [
        [
         { "params": [ "p50" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Services - 99th percentile FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]] (slot [[tag_slot]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "scenario" ], "type": "tag" },
        { "params": [ "serviceName" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "service_FAIL_histogram",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Services - throughput FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "alias": "$tag_scenario - $tag_serviceName",
       "query": "SELECT sum(mean)\nFROM (\n  SELECT mean(value)\n  FROM \"service_FAIL_instantRate\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, serviceName, slot\n)\nGROUP BY time($__interval), scenario, serviceName"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "RocksDB cur-size-all-mem-tables",
     "type": "graph",
     "description": "Estimates of RocksDB state size. Aggregates (such as session windows) can have many internal states, which are reported separately. ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_operator_name]] ($0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "operator_name" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^.*.cur-size-all-mem-tables/",
       "query": "\nSELECT sum(\"value\")\nFROM (\n   SELECT mean(\"value\") AS \"value\"\n   FROM /^.*.cur-size-all-mem-tables/ \n   WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter \n   GROUP BY time($__interval), \"scenario\", \"operator_name\", \"slot\"\n) GROUP BY time($__interval), \"scenario\", \"operator_name\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RocksDB estimate-live-data-size",
     "type": "graph",
     "description": "Estimates of RocksDB state size. Aggregates (such as session windows) can have many internal states, which are reported separately. ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_operator_name]] ($0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "operator_name" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^.*.cur-size-all-mem-tables/",
       "query": "SELECT sum(\"value\")\nFROM (\n   SELECT mean(\"value\") AS \"value\"\n   FROM /^.*.estimate-live-data-size/ \n   WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n   GROUP BY time($__interval), \"scenario\", \"operator_name\", \"slot\"\n) GROUP BY time($__interval), \"scenario\", \"operator_name\" fill(linear)\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RocksDB estimate-num-keys",
     "type": "graph",
     "description": "Estimates on number of keys in RocksDB state. Aggregates (e.g. session windows) can have many internal states. Please remember that this is only estimate, based on internal RocksDB metrics",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_operator_name]] ($0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "operator_name" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^.*.estimate-num-keys/",
       "query": "SELECT sum(\"value\")\nFROM (\n   SELECT mean(\"value\") AS \"value\"\n   FROM /^.*.estimate-num-keys/ \n   WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter \n   GROUP BY time($__interval), \"scenario\", \"operator_name\", \"slot\"\n) GROUP BY time($__interval), \"scenario\", \"operator_name\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Scenario health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jobmanager_job_uptime",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of restarts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jobmanager_job_fullRestarts",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Last checkpoint duration",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "jobmanager_job_lastCheckpointDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Last checkpoint size",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "jobmanager_job_lastCheckpointSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Completed checkpoints",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jobmanager_job_numberOfCompletedCheckpoints",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Failed checkpoints",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jobmanager_job_numberOfFailedCheckpoints",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}