openapi: "3.1.0"
info:
  title: Simple API overview
  version: 2.0.0
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /customer:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
