openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /customer:
    post:
      summary:  Returns ComponentsBykeys.
      requestBody:
        description:
          Keys of the Customers.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultiKeys'
      responses:
        '201':
          description:
            OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'

components:
  schemas:
    MultiKeys:
      type: array
      minItems: 1
      items:
        type: object
        properties:
          primaryKey:
            type: string
          additionalKey:
            type: string
          validFor:
            type: integer
            format: int64
            minimum: 1
            maximum: 2592000
        required:
          - primaryKey
          - additionalKey
    Customer:
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        id:
          type: integer
