package pl.touk.nussknacker.engine.api.test

import io.circe.Json

/**
 * Holds test records generated by a single source.
 */
case class TestData(testRecords: List[TestRecord])

/**
 * Test record represented as a JSON
 * @param timestamp is used to order records generated by different sources in a scenario. Records without timestamp should be read last.
 */
case class TestRecord(json: Json, timestamp: Option[Long] = None)

