package pl.touk.nussknacker.engine.api.test

import pl.touk.nussknacker.engine.api.test.TestParameters.TestParameterDefinitions
import pl.touk.nussknacker.engine.graph.expression.Expression

/**
 * Test record represented as a Map[String, Expression] - [source name, param expression]
 * @param timestamp is used to order records generated by different sources in a scenario. Records without timestamp should be read last.
 */
case class TestParameters(parameters: TestParameterDefinitions, timestamp: Option[Long] = None)
object TestParameters {
  type TestParameterDefinitions = Map[String, Expression]
}