{
 "title": "Flink-ESP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "processName",
    "query": "SHOW TAG VALUES FROM \"source.instantRate\" WITH KEY = \"process\""
   },
   {
    "name": "env",
    "query": "SHOW TAG VALUES FROM \"source.instantRate\" WITH KEY = \"env\""
   }
  ]
 },
 "panels": [
  {
   "title": "Source throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "source.instantRate",
     "query": "SELECT sum(\"value\") FROM \"source.instantRate\" WHERE \"process\" =~ /$processName$/ AND \"host\" =~ /$hosts$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=~", "value": "/$processName$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Events that passed whole process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]] - [[tag_action]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "end.instantRate",
     "query": "SELECT sum(\"value\") FROM \"end.instantRate\" WHERE \"process\" =~ /$processName$/ AND \"host\" =~ /$hosts$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=~", "value": "/$processName$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Rejected events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]-[[tag_action]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dead_end.instantRate",
     "query": "SELECT sum(\"value\") FROM \"dead_end.instantRate\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($interval), \"process\", \"action\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=~", "value": "/$processName$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "[[tag_process]] - ALL EVENTS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "source.instantRate",
     "query": "SELECT sum(\"value\") FROM \"dead_end.instantRate\" WHERE \"process\" =~ /$processName$/ AND \"host\" =~ /$hosts$/ AND $timeFilter GROUP BY time($interval), \"process\", \"action\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=~", "value": "/$processName$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP services - median OK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_action]] - median OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"serviceTimes.OK.p50\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($interval), \"process\", \"action\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP services - 99% percentile OK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_action]] - p99 OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"serviceTimes.OK.p99\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($interval), \"process\", \"action\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP services - throughput OK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_action OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serviceInstant.OK",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=~", "value": "/^$processName$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP services - median FAIL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_action]] - median FAIL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"serviceTimes.FAIL.p50\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($interval), \"process\", \"action\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP services - 99% percentile FAIL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_action]] - p99 FAIL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"serviceTimes.FAIL.p99\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($interval), \"process\", \"action\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP services - throughput FAIL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_action FAIL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serviceInstant.FAIL",
     "query": "SELECT mean(\"value\") FROM \"serviceInstant.OK\" WHERE \"process\" =~ /^$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($interval), \"process\", \"action\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=~", "value": "/^$processName$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "error.instantRate",
     "query": "SELECT sum(\"value\") FROM \"error.instantRate\" WHERE \"process\" =~ /$processName$/ AND \"host\" =~ /$hosts$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=~", "value": "/$processName$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Lag on Kafka source (events)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "records-lag-max",
     "query": "SELECT max(\"value\") FROM \"records-lag-max\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - minimum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay.min",
     "query": "SELECT min(\"value\") FROM \"eventtimedelay.min\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - median",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay.p50",
     "query": "SELECT mean(\"value\") FROM \"eventtimedelay.p50\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - maximum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay.max",
     "query": "SELECT max(\"value\") FROM \"eventtimedelay.max\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time from latest event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_process]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay.minimalDelay",
     "query": "SELECT min(\"value\") FROM \"eventtimedelay.min\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
     ]
    }
   ]
  }
 ]
}