{
 "title": "Scenario",
 "time": { "from": "2021-06-22T11:34:20.620Z", "to": "2021-06-22T12:34:20.620Z" },
 "templating": {
  "list": [
   {
    "name": "processName",
    "query": "SHOW TAG VALUES FROM \"source_instantRate\" WITH KEY = \"process\""
   },
   {
    "name": "env",
    "query": "SHOW TAG VALUES FROM \"source_instantRate\" WITH KEY = \"env\""
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,3m, 10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Basics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "source.instantRate",
       "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"source_count\"\n  WHERE process =~ /^$processName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), process, slot\n)\nGROUP BY time($__interval), process\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "process", "operator": "=~", "value": "/$processName$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/$env$/" }
       ]
      }
     ]
    },
    {
     "title": "Events that passed whole process /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]] - [[tag_nodeId]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "nodeId" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "end.instantRate",
       "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"end_count\"\n  WHERE process =~ /^$processName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), process, nodeId, slot\n)\nGROUP BY time($__interval), process, nodeId\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "process", "operator": "=~", "value": "/$processName$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
       ]
      }
     ]
    },
    {
     "title": "Rejected events /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]] - [[tag_nodeId]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "nodeId" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dead_end.instantRate",
       "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"dead_end_count\"\n  WHERE process =~ /^$processName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), process, nodeId, slot\n)\nGROUP BY time($__interval), process, nodeId\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "process", "operator": "=~", "value": "/$processName$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]] - [[tag_action]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "error.instantRateByNode.count.count",
       "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"error_instantRateByNode_count\"\n  WHERE process =~ /^$processName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), process, slot\n)\nGROUP BY time($__interval), process, nodeId\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "process", "operator": "=~", "value": "/$processName$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
       ]
      }
     ]
    },
    {
     "title": "Max lag among Kafka source partitions (events)",
     "type": "graph",
     "description": "IMPORTANT. \nThis metric does NOT show the overall lag on Kafka source; a largest lag among all the source partitions is shown.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_process",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" }
       ],
       "measurement": "records-lag-max",
       "query": "SELECT max(\"value\") FROM \"records-lag-max\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
       ]
      }
     ]
    },
    {
     "title": "Delay since event occurrence - minimum",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "eventtimedelay_histogram",
       "query": "SELECT min(\"min\") FROM \"eventtimedelay_histogram\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
       "select": [
        [
         { "params": [ "min" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
       ]
      }
     ]
    },
    {
     "title": "Delay since event occurrence - median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "eventtimedelay_histogram",
       "query": "SELECT mean(\"p50\") FROM \"eventtimedelay_histogram\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
       "select": [
        [
         { "params": [ "p50" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
       ]
      }
     ]
    },
    {
     "title": "Delay since event occurrence - maximum",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "eventtimedelay_histogram",
       "query": "SELECT max(\"max\") FROM \"eventtimedelay_histogram\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
       "select": [
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
       ]
      }
     ]
    },
    {
     "title": "Time from latest event",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "eventtimedelay_minimalDelay",
       "query": "SELECT min(\"value\") FROM \"eventtimedelay_histogram\" WHERE \"host\" =~ /$hosts$/ AND \"process\" =~ /$processName$/ AND $timeFilter GROUP BY time($interval), \"process\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "process", "operator": "=~", "value": "/$processName$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "External services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP services - median OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]] - [[tag_serviceName]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"p50\") FROM \"service_OK_histogram\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($__interval), \"process\", \"serviceName\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP services - 99th percentile OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]] - [[tag_serviceName]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"p99\") FROM \"service_OK_histogram\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($__interval), \"process\", \"serviceName\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP services - throughput OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]] - [[tag_serviceName]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "action" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "serviceInstant.OK",
       "query": "SELECT sum(mean)\nFROM (\n  SELECT mean(value)\n  FROM \"service_OK_instantRate\"\n  WHERE process =~ /^$processName$/ AND env = '$env'\n  GROUP BY time($__interval), process, serviceName, slot\n)\nWHERE $timeFilter\nGROUP BY time($__interval), process, serviceName",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "process", "operator": "=~", "value": "/^$processName$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
       ]
      }
     ]
    },
    {
     "title": "HTTP services - median FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]] - [[tag_serviceName]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"p50\") FROM \"service_FAIL_histogram\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($__interval), \"process\", \"serviceName\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP services - 99th percentile FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_process]] - [[tag_serviceName]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"p99\") FROM \"service_FAIL_histogram\" WHERE \"process\" =~ /$processName$/ AND \"env\" =~ /^$env$/ AND $timeFilter GROUP BY time($__interval), \"process\", \"serviceName\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP services - throughput FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "alias": "$tag_process - $tag_serviceName",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "process" ], "type": "tag" },
        { "params": [ "action" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "serviceInstant.FAIL",
       "query": "SELECT sum(mean)\nFROM (\n  SELECT mean(value)\n  FROM \"service_FAIL_instantRate\"\n  WHERE process =~ /^$processName$/ AND env = '$env'\n  GROUP BY time($__interval), process, serviceName, slot\n)\nWHERE $timeFilter\nGROUP BY time($__interval), serviceName, action",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "process", "operator": "=~", "value": "/^$processName$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RocksDB data size",
     "type": "graph",
     "description": "Estimates of RocksDB state size. Aggregates (such as session windows) can have many internal states, which are reported separately. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$m [[tag_operator_name]] [[tag_slot]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "operator_name" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^.*.cur-size-all-mem-tables/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$m [[tag_operator_name]] [[tag_slot]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "operator_name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^.*.estimate-live-data-size/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RocksDB keys size",
     "type": "graph",
     "description": "Estimates on number of keys in RocksDB state. Aggregates (e.g. session windows) can have many internal states. Please remember that this is only estimate, based on internal RocksDB metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$m [[tag_operator_name]] [[tag_slot]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "operator_name" ], "type": "tag" },
        { "params": [ "slot" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^.*.estimate-num-keys/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Scenario health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/^$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of restarts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_fullRestarts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/^$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Last checkpoint duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_lastCheckpointDuration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/^$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Last checkpoint duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_lastCheckpointSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/^$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Completed checkpoints",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_numberOfCompletedCheckpoints",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/^$processName$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed checkpoints",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobmanager_job_numberOfFailedCheckpoints",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "process", "operator": "=~", "value": "/^$processName$/" }
     ]
    }
   ]
  }
 ]
}