export enum WindowKind {
    default,
    confirm,
    inform,
    viewNode,
    editNode,
    addProcess,
    addfragment,
    saveProcess,
    deployProcess,
    calculateCounts,
    generateTestData,
    generateDataAndTest,
    compareVersions,
    customAction,
    genericAction,
    survey,
}
