export enum WindowKind {
  default,
  confirm,
  inform,
  viewNode,
  editNode,
  addProcess,
  addSubProcess,
  saveProcess,
  deployProcess,
  calculateCounts,
  generateTestData,
  generateDataAndTest,
  compareVersions,
  customAction,
  genericAction,
  survey,
}
