# taskmanager.numberOfTaskSlots will be set by Flink's entrypoint script

jobmanager.memory.flink.size: 800m
taskmanager.memory.flink.size: 800m
taskmanager.memory.jvm-metaspace.size: 512m
env.java.default-opts.all: >-
  --add-opens=java.base/java.nio.charset=ALL-UNNAMED
  --add-opens=java.base/sun.nio.cs=ALL-UNNAMED
  --add-opens=java.sql/java.sql=ALL-UNNAMED
