package pl.touk.nussknacker.engine.flink.api.process

import org.apache.flink.api.common.eventtime.WatermarkStrategy
import org.apache.flink.streaming.api.datastream.{DataStream, SingleOutputStreamOperator}
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment
import pl.touk.nussknacker.engine.api.Context
import pl.touk.nussknacker.engine.api.process.{BasicContextInitializer, ContextInitializer, Source, SourceTestSupport}
import pl.touk.nussknacker.engine.api.typed.typing.Unknown
import pl.touk.nussknacker.engine.flink.api.compat.ExplicitUidInOperatorsSupport

/**
  * Source with methods specific for Flink
  */
trait FlinkSource extends Source {

  def contextStream(
      env: StreamExecutionEnvironment,
      flinkNodeContext: FlinkCustomNodeContext
  ): DataStream[Context]

}

/**
  * Support for test mechanism for typical flink sources.
  *
  * @tparam Raw - type of raw event that is generated by flink source function.
  *             This is needed to handle e.g. syntax suggestions in UI (in sources with explicite @MethodToInvoke).
  */
trait FlinkSourceTestSupport[Raw] extends SourceTestSupport[Raw] {
  self: Source =>

  // TODO: design better way of handling test data in generic FlinkSource
  // Probably we *still* want to use CollectionSource (and have some custom logic in parser if needed), but timestamps
  // have to be handled here for now
  def watermarkStrategyForTest: Option[WatermarkStrategy[Raw]]

}

/**
 * Source providing standard logic for transforming a `DataStreamSource[Raw]` into `DataStream[Context]` using
 * customizable [[ContextInitializer]] and [[WatermarkStrategy]].
 *
 * @tparam Raw - type of raw event that is generated by flink source function.
 */
trait StandardFlinkSource[Raw]
    extends FlinkSource
    with BaseFlinkSource
    with CustomizableContextInitializerSource[Raw]
    with CustomizableWatermarkStrategySource[Raw]
    with ExplicitUidInOperatorsSupport {

  protected def sourceStream(
      env: StreamExecutionEnvironment,
      flinkNodeContext: FlinkCustomNodeContext
  ): DataStream[Raw]

  override final def contextStream(
      env: StreamExecutionEnvironment,
      flinkNodeContext: FlinkCustomNodeContext
  ): DataStream[Context] = {
    val streamOfRaw = sourceStream(env, flinkNodeContext)
    // 1. set UID and override source name
    // 2. assign timestamp and watermark policy
    val rawSourceWithUidAndTimestamp = sourceWithUidAndTimestamp(
      streamOfRaw,
      flinkNodeContext,
      watermarkStrategy,
    )

    // 3. initialize Context and spool Context to the stream
    rawSourceWithUidAndTimestamp
      .map(
        new FlinkContextInitializingFunction(
          contextInitializer,
          flinkNodeContext.nodeId,
          flinkNodeContext.convertToEngineRuntimeContext
        ),
        flinkNodeContext.contextTypeInfo
      )
  }

}

trait BaseFlinkSource { this: ExplicitUidInOperatorsSupport =>

  def sourceWithUidAndTimestamp[T](
      streamOfRaw: DataStream[T],
      flinkNodeContext: FlinkCustomNodeContext,
      watermarkStrategy: Option[WatermarkStrategy[T]]
  ): DataStream[T] = {
    val rawSourceWithUid = streamOfRaw match {
      case singleOut: SingleOutputStreamOperator[_] =>
        setUidToNodeIdIfNeed[T](
          flinkNodeContext,
          singleOut.name(flinkNodeContext.nodeId.id)
        )
      case _ => streamOfRaw
    }
    watermarkStrategy
      .map(rawSourceWithUid.assignTimestampsAndWatermarks)
      .getOrElse(rawSourceWithUid)
  }

}

trait CustomizableContextInitializerSource[Raw] { self: Source =>
  def contextInitializer: ContextInitializer[Raw] = new BasicContextInitializer[Raw](Unknown)
}

trait CustomizableWatermarkStrategySource[Raw] { self: Source =>
  def watermarkStrategy: Option[WatermarkStrategy[Raw]] = None
}
