package pl.touk.nussknacker.engine.api.process

import cats.data.ValidatedNel
import pl.touk.nussknacker.engine.api.context.ProcessCompilationError.NodeId
import pl.touk.nussknacker.engine.api.context.{ProcessCompilationError, ValidationContext}
import pl.touk.nussknacker.engine.api.typed.typing.TypingResult
import pl.touk.nussknacker.engine.api.{Context, VariableConstants}

/**
  * ContextInitializer provides implementation of transformation from raw event generated by source to Context.
  *
  * @tparam Raw - type of raw event that is generated by source (KafkaDeserializationSchema for kafka) in source function.
  */
trait ContextInitializer[Raw] extends Serializable {

  /**
    * Initializes `Context` with raw event value.
    *
    * @param processId - id of the process, used to setup name of created Context
    * @param nodeId  - name of node, used to setup name of created Context
    */
  def initContext(processId: String, nodeId: String): ContextInitializingFunction[Raw]

  /**
    * Enhances validation context with definition of all variables produced by the source.
    *
    * @param context      - `ValidationContext` initialized with global variables, definition of variables available in `Context` scope and their types
    * @return - validation context with initialized "input" variable.
    */
  def validationContext(context: ValidationContext)(implicit nodeId: NodeId): ValidatedNel[ProcessCompilationError, ValidationContext]

}

trait ContextInitializingFunction[Raw] extends (Raw => Context) with Serializable

/**
  * Basic implementation of context initializer. Used when raw event produced by source does not need further transformations and
  * should be assigned to default "input" variable directly.
  *
  * @tparam Raw - type of raw event that is generated by source (KafkaDeserializationSchema for kafka) in source function.
  */
class BasicContextInitializer[Raw](protected val outputVariableType: TypingResult, protected val outputVariableName: String = VariableConstants.InputMetaVariableName) extends ContextInitializer[Raw] {

  // processId, nodeId is needed?
  override def initContext(processId: String, nodeId: String): ContextInitializingFunction[Raw] =
    BasicContextInitializingFunction(processId, nodeId, outputVariableName)

  protected def newContext(processId: String, nodeId: String): Context = {
    Context.withPrefixedInitialId(s"$processId-$nodeId")
  }

  override def validationContext(context: ValidationContext)(implicit nodeId: NodeId): ValidatedNel[ProcessCompilationError, ValidationContext] = {
    context.withVariable(outputVariableName, outputVariableType, None)
  }

}

/**
  * Initialize context of variables based on "input" variable represents the event.
  *
  * @param processId - id of the process or flink job, used to setup name of created Context
  * @param nodeId  - name of node, used to setup name of created Context
  * @param outputVariableName - name of output variable
  * @tparam Raw - type of raw event that is generated by source (KafkaDeserializationSchema for kafka) in source function.
  */
case class BasicContextInitializingFunction[Raw](processId: String, nodeId: String, outputVariableName: String) extends ContextInitializingFunction[Raw] {

  override def apply(input: Raw): Context =
    newContext(processId, nodeId).withVariable(outputVariableName, input)

  protected def newContext(processId: String, nodeId: String): Context = {
    Context.withPrefixedInitialId(s"$processId-$nodeId")
  }

}