package pl.touk.nussknacker.engine.api.process

import pl.touk.nussknacker.engine.api.MethodToInvoke
import pl.touk.nussknacker.engine.api.component.Component
import pl.touk.nussknacker.engine.api.test.TestDataParser

import scala.reflect.{ClassTag, classTag}

/**
  * Common trait for source of events. For Flink see pl.touk.nussknacker.engine.flink.api.process.FlinkSource
  *
  * @tparam T - type of event that is generated by this source. This is needed to handle e.g. syntax suggestions in UI
  */
trait Source[+T] {

}

/**
  * Support for test source functionality. Uses [[pl.touk.nussknacker.engine.api.test.TestDataParser]] to define
  * how test data are provided to the source.
  * @tparam T - type of event that is generated by the source.
  */
trait SourceTestSupport[+T] { self: Source[T] =>
  def testDataParser: TestDataParser[T]
}

/**
  * Optional support for test source functionality. Defines how test data should be prepared,
  * in a way that is recognized further by [[pl.touk.nussknacker.engine.api.test.TestDataParser]].
  */
trait TestDataGenerator { self: Source[_] with SourceTestSupport[_] =>
  def generateTestData(size: Int) : Array[Byte]
}

/**
  * [[pl.touk.nussknacker.engine.api.process.SourceFactory]] has to have method annotated with [[pl.touk.nussknacker.engine.api.MethodToInvoke]]
  * that returns [[pl.touk.nussknacker.engine.api.process.Source]]
  * IMPORTANT lifecycle notice:
  * Implementations of this class *must not* allocate resources (connections, file handles etc.)
  * TODO: remove T parameter from SourceFactory and Source, it's no longer needed in general case
  */
trait SourceFactory[+T] extends Serializable with Component

object SourceFactory {

  def noParam[T: ClassTag](source: Source[T]): SourceFactory[T] =
    new NoParamSourceFactory[T](source)

  case class NoParamSourceFactory[T: ClassTag](source: Source[T]) extends SourceFactory[T] {

    @MethodToInvoke
    def create(): Source[T] = source
  }
}
