package pl.touk.nussknacker.engine.api.deployment

import io.circe.{Decoder, Encoder}
import io.circe.generic.extras.semiauto._

//id generated by Nussknacker - vide ExternalDeploymentId for id generated by e.g. Flink
final case class DeploymentId(value: String) extends AnyVal

object DeploymentId {
  implicit val encoder: Encoder[DeploymentId] = deriveUnwrappedEncoder
  implicit val decoder: Decoder[DeploymentId] = deriveUnwrappedDecoder
}