/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.touk.nussknacker.engine.avro.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SampleLocation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8582896089077227274L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SampleLocation\",\"namespace\":\"pl.touk.nussknacker.engine.avro.schema\",\"fields\":[{\"name\":\"x_pos\",\"type\":\"long\"},{\"name\":\"y_pos\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SampleLocation> ENCODER =
      new BinaryMessageEncoder<SampleLocation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SampleLocation> DECODER =
      new BinaryMessageDecoder<SampleLocation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SampleLocation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SampleLocation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SampleLocation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SampleLocation>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SampleLocation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SampleLocation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SampleLocation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SampleLocation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long x_pos;
   private long y_pos;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SampleLocation() {}

  /**
   * All-args constructor.
   * @param x_pos The new value for x_pos
   * @param y_pos The new value for y_pos
   */
  public SampleLocation(Long x_pos, Long y_pos) {
    this.x_pos = x_pos;
    this.y_pos = y_pos;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return x_pos;
    case 1: return y_pos;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: x_pos = (Long)value$; break;
    case 1: y_pos = (Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'x_pos' field.
   * @return The value of the 'x_pos' field.
   */
  public long getXPos() {
    return x_pos;
  }


  /**
   * Sets the value of the 'x_pos' field.
   * @param value the value to set.
   */
  public void setXPos(long value) {
    this.x_pos = value;
  }

  /**
   * Gets the value of the 'y_pos' field.
   * @return The value of the 'y_pos' field.
   */
  public long getYPos() {
    return y_pos;
  }


  /**
   * Sets the value of the 'y_pos' field.
   * @param value the value to set.
   */
  public void setYPos(long value) {
    this.y_pos = value;
  }

  /**
   * Creates a new SampleLocation RecordBuilder.
   * @return A new SampleLocation RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new SampleLocation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SampleLocation RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new SampleLocation RecordBuilder by copying an existing SampleLocation instance.
   * @param other The existing instance to copy.
   * @return A new SampleLocation RecordBuilder
   */
  public static Builder newBuilder(SampleLocation other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for SampleLocation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SampleLocation>
    implements org.apache.avro.data.RecordBuilder<SampleLocation> {

    private long x_pos;
    private long y_pos;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.x_pos)) {
        this.x_pos = data().deepCopy(fields()[0].schema(), other.x_pos);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.y_pos)) {
        this.y_pos = data().deepCopy(fields()[1].schema(), other.y_pos);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing SampleLocation instance
     * @param other The existing instance to copy.
     */
    private Builder(SampleLocation other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.x_pos)) {
        this.x_pos = data().deepCopy(fields()[0].schema(), other.x_pos);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.y_pos)) {
        this.y_pos = data().deepCopy(fields()[1].schema(), other.y_pos);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'x_pos' field.
      * @return The value.
      */
    public long getXPos() {
      return x_pos;
    }


    /**
      * Sets the value of the 'x_pos' field.
      * @param value The value of 'x_pos'.
      * @return This builder.
      */
    public Builder setXPos(long value) {
      validate(fields()[0], value);
      this.x_pos = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'x_pos' field has been set.
      * @return True if the 'x_pos' field has been set, false otherwise.
      */
    public boolean hasXPos() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'x_pos' field.
      * @return This builder.
      */
    public Builder clearXPos() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'y_pos' field.
      * @return The value.
      */
    public long getYPos() {
      return y_pos;
    }


    /**
      * Sets the value of the 'y_pos' field.
      * @param value The value of 'y_pos'.
      * @return This builder.
      */
    public Builder setYPos(long value) {
      validate(fields()[1], value);
      this.y_pos = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'y_pos' field has been set.
      * @return True if the 'y_pos' field has been set, false otherwise.
      */
    public boolean hasYPos() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'y_pos' field.
      * @return This builder.
      */
    public Builder clearYPos() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SampleLocation build() {
      try {
        SampleLocation record = new SampleLocation();
        record.x_pos = fieldSetFlags()[0] ? this.x_pos : (Long) defaultValue(fields()[0]);
        record.y_pos = fieldSetFlags()[1] ? this.y_pos : (Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SampleLocation>
    WRITER$ = (org.apache.avro.io.DatumWriter<SampleLocation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SampleLocation>
    READER$ = (org.apache.avro.io.DatumReader<SampleLocation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.x_pos);

    out.writeLong(this.y_pos);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.x_pos = in.readLong();

      this.y_pos = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.x_pos = in.readLong();
          break;

        case 1:
          this.y_pos = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










