name: nussknacker-dev

services:

  ### Wait for other images

  wait-for-all:
    image: busybox:1.36.1
    entrypoint: /bin/sh -c "tail -f /dev/null"
    depends_on:
      postgres:
        condition: service_healthy
      grafana:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      akhq:
        condition: service_healthy
      flink-jobmanager:
        condition: service_healthy
      telegraf:
        condition: service_healthy

  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "nu-db"
      POSTGRES_USER: "nu"
      POSTGRES_PASSWORD: "nupassword"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d nu-db -U nu"]
      interval: 10s
      retries: 10
    volumes:
      - nussknacker_designer_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M

  ### Nussknacker metrics-related services:

  grafana:
    image: grafana/grafana:10.1.10
    restart: unless-stopped
    ports:
      - 8081:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:/grafana"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000"]
      interval: 10s
      retries: 10
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    deploy:
      resources:
        limits:
          memory: 256M

  influxdb:
    image: influxdb:1.8.10
    restart: unless-stopped
    ports:
      - 3086:8086
    environment:
      INFLUXDB_DB: "nussknacker_metrics"
    healthcheck:
      test: [ "CMD-SHELL", "influx -execute 'SHOW DATABASES'" ]
      interval: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 128M

  ### KAFKA-related services:

  kafka:
    image: bitnami/kafka:3.7.0
    restart: unless-stopped
    hostname: nu-kafka
    ports:
      - 3032:9092
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M

  schema-registry:
    image: bitnami/schema-registry:7.6.1
    restart: unless-stopped
    ports:
      - 3082:8081
    environment:
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_KAFKA_BROKERS: "PLAINTEXT://kafka:9092"
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", 'echo -e "GET /subjects HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" | nc localhost 8081 | grep -q "HTTP/1.1 200 OK" | exit 0']
      interval: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 384M

  akhq:
    image: tchiotludo/akhq:0.24.0
    restart: unless-stopped
    ports:
      - 18080:8080
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          server:
            context-path: /akhq
        akhq:
          connections:
            nussknacker-kafka:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8081"
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080" ]
      interval: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 256M

  ### FLINK-related services

  flink-jobmanager:
    build:
      context: flink/
      args:
        FLINK_VERSION: "1.18.1-scala_2.12-java11"
    restart: unless-stopped
    command: jobmanager
    ports:
      - 3031:8081
    environment:
      JOB_MANAGER_RPC_ADDRESS: "flink-jobmanager"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/jobs/overview" ]
      interval: 10s
      retries: 10
    volumes:
      - nussknacker_flink_data:/opt/flink/data

  flink-taskmanager:
    build:
      context: flink/
      args:
        FLINK_VERSION: "1.18.1-scala_2.12-java11"
    restart: unless-stopped
    command: taskmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: "flink-jobmanager"
    depends_on:
      flink-jobmanager:
        condition: service_healthy
      telegraf:
        condition: service_healthy
    volumes_from:
      - flink-jobmanager
    deploy:
      resources:
        limits:
          memory: 1024M

  telegraf:
    image: telegraf:1.30.2
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8087/write" ]
      interval: 10s
      retries: 10
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  nussknacker_designer_data:
    name: nussknacker_designer_data
  nussknacker_flink_data:
    name: nussknacker_flink_data
