deploymentConfig {
  type: "test"
}

modelConfig {
  rocksDB: {
    // TODO: we should test more common case - with rocksdb turned on. See designer/README.md for details how
    enable: false
  }
  liveDataPreview {
    enabled: true
    maxNumberOfRecords: 20
    throughputTimeWindowInSeconds: 60
    storage {
      type: "DESIGNER_DB"
      uploadIntervalInSeconds: 1
      url: "jdbc:hsqldb:file:"${storageDir}"/db;sql.syntax_ora=true"
      url: ${?DB_URL}
      user: "SA"
      user: ${?DB_USER}
      password: ""
      password: ${?DB_PASSWORD}
      schema: "public"
    }
  }
}
