#!/usr/bin/env sh

if git diff --cached --name-only --diff-filter=ACM | grep --max-count=1 -E "^designer/(client|submodules)/" > /dev/null; then
  (cd designer/ && ./formatStagedFrontendFiles.sh)
fi

# fixme: will be enabled in the next PR
#if git diff --cached --name-only --diff-filter=ACM | grep -E --max-count=1 '\.scala$|\.sbt$' > /dev/null; then
#  ./sbtwrapper formatStagedScalaFiles
#fi