import { extendActivitiesWithUIData } from "./extendActivitiesWithUIData";
import { mergeActivityDataWithMetadata } from "./mergeActivityDataWithMetadata";
import { sampleMetadataResponse } from "../../../../../__mocks__/fixtures/sampleMetadataResponse";
import { sampleActivitiesResponse, sampleActivitiesWithRepetiveResponse } from "../../../../../__mocks__/fixtures/sampleActivitiesResponse";
import { ActivitiesResponse } from "../types";

describe("extendActivitiesWithUIData", () => {
    it("should render activities with metadata when items are not grouped", () => {
        const activitiesDataWithMetadata = mergeActivityDataWithMetadata(sampleActivitiesResponse, sampleMetadataResponse);

        const expected = [
            {
                uiType: "date",
                value: "2024-09-26",
            },
            {
                actions: [],
                activities: {
                    displayableName: "Scenario unarchived",
                    icon: "/assets/process/success.svg",
                    supportedActions: [],
                    type: "SCENARIO_UNARCHIVED",
                },
                additionalFields: [],
                attachment: null,
                comment: null,
                date: "2024-09-26T10:26:42.999982Z",
                id: "1ba9d6c6-c61a-42f5-8311-4d0f287867f7",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: null,
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 6,
                type: "SCENARIO_UNARCHIVED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [],
                activities: {
                    displayableName: "Scenario archived",
                    icon: "/assets/process/archived.svg",
                    supportedActions: [],
                    type: "SCENARIO_ARCHIVED",
                },
                additionalFields: [],
                attachment: null,
                comment: null,
                date: "2024-09-26T10:26:28.293423Z",
                id: "ec245dc5-f84c-4880-8727-b8c999c35a3f",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: null,
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 6,
                type: "SCENARIO_ARCHIVED",
                uiType: "item",
                user: "admin",
            },
            {
                uiType: "date",
                value: "2024-09-25",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "122",
                    },
                    lastModifiedAt: "2024-09-25T09:55:04.309Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-25T09:55:04.309Z",
                id: "15c0e8a9-d1c5-47dd-bf28-8a08217fff5b",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: "Version 4 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 4,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                uiType: "date",
                value: "2024-09-22",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "tests save",
                    },
                    lastModifiedAt: "2024-09-22T09:53:40.875721Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-22T09:53:40.875721Z",
                id: "a2576467-9bf9-4a92-b71f-be95b84d59f6",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: "Version 3 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 3,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                uiType: "date",
                value: "2022-01-22",
            },
            {
                actions: [
                    {
                        displayableName: "Download",
                        icon: "/assets/states/error.svg",
                        id: "download_attachment",
                    },
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_attachment",
                    },
                ],
                activities: {
                    displayableName: "Attachment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["download_attachment", "delete_attachment"],
                    type: "ATTACHMENT_ADDED",
                },
                additionalFields: [],
                attachment: {
                    file: {
                        id: 1,
                        status: "AVAILABLE",
                    },
                    filename: "324.log",
                    lastModifiedAt: "2022-01-22T06:09:44.313094Z",
                    lastModifiedBy: "admin",
                },
                comment: null,
                date: "2022-01-22T06:09:44.313094Z",
                id: "48f383f9-ccdd-46b6-9b33-5f6693165755",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: null,
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 1,
                type: "ATTACHMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
        ];

        expect(extendActivitiesWithUIData(activitiesDataWithMetadata)).toMatchObject(expected);
    });
    it("should render activities with metadata and date range when items are grouped in the date range", () => {
        const activitiesDataWithMetadata = mergeActivityDataWithMetadata(sampleActivitiesWithRepetiveResponse, sampleMetadataResponse);

        const expected = [
            {
                uiType: "date",
                value: ["2024-09-25", "2024-09-26"],
            },
            {
                actions: [],
                activities: {
                    displayableName: "Scenario unarchived",
                    icon: "/assets/process/success.svg",
                    supportedActions: [],
                    type: "SCENARIO_UNARCHIVED",
                },
                additionalFields: [],
                attachment: null,
                comment: null,
                date: "2024-09-26T10:26:42.999982Z",
                id: "1ba9d6c6-c61a-42f5-8311-4d0f287867f7",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: null,
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 6,
                type: "SCENARIO_UNARCHIVED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [],
                activities: {
                    displayableName: "Scenario archived",
                    icon: "/assets/process/archived.svg",
                    supportedActions: [],
                    type: "SCENARIO_ARCHIVED",
                },
                additionalFields: [],
                attachment: null,
                comment: null,
                date: "2024-09-26T10:26:28.293423Z",
                id: "ec245dc5-f84c-4880-8727-b8c999c35a3f",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: null,
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 6,
                type: "SCENARIO_ARCHIVED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "Scenario migrated from local by admin",
                    },
                    lastModifiedAt: "2024-09-26T10:22:45.494475Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-26T10:22:45.494475Z",
                id: "4e8c9f40-7c2c-434e-8528-68dccf66d5d1",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: "Version 6 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 6,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "Scenario migrated from local by admin",
                    },
                    lastModifiedAt: "2024-09-26T10:13:11.571064Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-26T10:13:11.571064Z",
                id: "35fa34fe-7f07-4b50-98fb-58d19d5b7704",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                overrideDisplayableName: "Version 6 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 6,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "Scenario migrated from local by admin",
                    },
                    lastModifiedAt: "2024-09-26T10:11:29.657265Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-26T10:11:29.657265Z",
                id: "c0745a74-937c-4682-b9c8-cb94f619eb14",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                overrideDisplayableName: "Version 6 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 6,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "test12345",
                    },
                    lastModifiedAt: "2024-09-26T10:08:00.895385Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-26T10:08:00.895385Z",
                id: "2cf1f252-3be1-413f-ad62-ccb311683744",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                overrideDisplayableName: "Version 6 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 6,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "test",
                    },
                    lastModifiedAt: "2024-09-26T07:17:19.892192Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-26T07:17:19.892192Z",
                id: "0182764d-c568-403e-88ea-24942a091af5",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                overrideDisplayableName: "Version 5 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 5,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "122",
                    },
                    lastModifiedAt: "2024-09-25T09:55:04.309Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-25T09:55:04.309Z",
                id: "15c0e8a9-d1c5-47dd-bf28-8a08217fff5b",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                overrideDisplayableName: "Version 4 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 4,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                    {
                        displayableName: "Compare",
                        icon: "/assets/states/error.svg",
                        id: "compare",
                    },
                ],
                activities: {
                    displayableName: "New version saved",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment", "compare"],
                    type: "SCENARIO_MODIFIED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "tests save",
                    },
                    lastModifiedAt: "2024-09-25T09:53:40.875721Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-25T09:53:40.875721Z",
                id: "a2576467-9bf9-4a92-b71f-be95b84d59f6",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                overrideDisplayableName: "Version 3 saved",
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 3,
                type: "SCENARIO_MODIFIED",
                uiType: "item",
                user: "admin",
            },
            {
                isClicked: false,
                sameItemOccurrence: 6,
                uiType: "toggleItemsButton",
            },
            {
                actions: [
                    {
                        displayableName: "Download",
                        icon: "/assets/states/error.svg",
                        id: "download_attachment",
                    },
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_attachment",
                    },
                ],
                activities: {
                    displayableName: "Attachment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["download_attachment", "delete_attachment"],
                    type: "ATTACHMENT_ADDED",
                },
                additionalFields: [],
                attachment: {
                    file: {
                        id: 1,
                        status: "AVAILABLE",
                    },
                    filename: "324.log",
                    lastModifiedAt: "2024-09-25T06:09:44.313094Z",
                    lastModifiedBy: "admin",
                },
                comment: null,
                date: "2024-09-25T06:09:44.313094Z",
                id: "48f383f9-ccdd-46b6-9b33-5f6693165755",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: null,
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 1,
                type: "ATTACHMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                ],
                activities: {
                    displayableName: "Comment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment"],
                    type: "COMMENT_ADDED",
                },
                additionalFields: [],
                attachment: null,
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "test",
                    },
                    lastModifiedAt: "2024-09-25T06:09:03.470213Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-09-25T06:09:03.470213Z",
                id: "56a7dd49-778b-468b-8e33-99bd176218aa",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                overrideDisplayableName: null,
                overrideIcon: null,
                overrideSupportedActions: null,
                scenarioVersionId: 1,
                type: "COMMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
        ];

        expect(extendActivitiesWithUIData(activitiesDataWithMetadata)).toMatchObject(expected);
    });

    it("should render activities with metadata without date range when items are grouped in the same day", () => {
        const activities: ActivitiesResponse["activities"] = [
            {
                id: "0a309251-9b98-4712-9d71-d5f31f0dd218",
                user: "admin",
                date: "2024-10-02T07:52:57.294963Z",
                scenarioVersionId: 13,
                comment: {
                    content: {
                        value: "test",
                        status: "AVAILABLE",
                    },
                    lastModifiedBy: "admin",
                    lastModifiedAt: "2024-10-02T07:52:57.294963Z",
                },
                additionalFields: [],
                type: "COMMENT_ADDED",
            },
            {
                id: "72ec0519-2b1e-4fa9-a589-ca41372f4b1d",
                user: "admin",
                date: "2024-10-02T08:41:02.637105Z",
                scenarioVersionId: 13,
                comment: {
                    content: {
                        value: "34",
                        status: "AVAILABLE",
                    },
                    lastModifiedBy: "admin",
                    lastModifiedAt: "2024-10-02T08:41:02.637105Z",
                },
                additionalFields: [],
                type: "COMMENT_ADDED",
            },
            {
                id: "c18a2e19-7a70-4150-bb12-eff61d21a2ed",
                user: "admin",
                date: "2024-10-02T08:48:39.822978Z",
                scenarioVersionId: 13,
                comment: {
                    content: {
                        value: "1",
                        status: "AVAILABLE",
                    },
                    lastModifiedBy: "admin",
                    lastModifiedAt: "2024-10-02T08:48:39.822978Z",
                },
                additionalFields: [],
                type: "COMMENT_ADDED",
            },
            {
                id: "c03cae2e-95e6-44ac-8d5d-6d253a8f669a",
                user: "admin",
                date: "2024-10-02T08:48:42.599853Z",
                scenarioVersionId: 13,
                comment: {
                    content: {
                        value: "2",
                        status: "AVAILABLE",
                    },
                    lastModifiedBy: "admin",
                    lastModifiedAt: "2024-10-02T08:48:42.599853Z",
                },
                additionalFields: [],
                type: "COMMENT_ADDED",
            },
            {
                id: "61f1c933-1c80-427f-b43d-39f5ae7a2b84",
                user: "admin",
                date: "2024-10-02T08:48:44.563111Z",
                scenarioVersionId: 13,
                comment: {
                    content: {
                        value: "3",
                        status: "AVAILABLE",
                    },
                    lastModifiedBy: "admin",
                    lastModifiedAt: "2024-10-02T08:48:44.563111Z",
                },
                additionalFields: [],
                type: "COMMENT_ADDED",
            },
            {
                id: "0bb4b537-6d17-4f65-999f-1ab3255621b6",
                user: "admin",
                date: "2024-10-02T08:48:46.816130Z",
                scenarioVersionId: 13,
                comment: {
                    content: {
                        value: "4",
                        status: "AVAILABLE",
                    },
                    lastModifiedBy: "admin",
                    lastModifiedAt: "2024-10-02T08:48:46.816130Z",
                },
                additionalFields: [],
                type: "COMMENT_ADDED",
            },
        ];
        const activitiesDataWithMetadata = mergeActivityDataWithMetadata(activities, sampleMetadataResponse);

        const expected = [
            {
                uiType: "date",
                value: "2024-10-02",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                ],
                activities: {
                    displayableName: "Comment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment"],
                    type: "COMMENT_ADDED",
                },
                additionalFields: [],
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "4",
                    },
                    lastModifiedAt: "2024-10-02T08:48:46.816130Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-10-02T08:48:46.816130Z",
                id: "0bb4b537-6d17-4f65-999f-1ab3255621b6",
                isActiveFound: false,
                isFound: false,
                isHidden: false,
                scenarioVersionId: 13,
                type: "COMMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                ],
                activities: {
                    displayableName: "Comment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment"],
                    type: "COMMENT_ADDED",
                },
                additionalFields: [],
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "3",
                    },
                    lastModifiedAt: "2024-10-02T08:48:44.563111Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-10-02T08:48:44.563111Z",
                id: "61f1c933-1c80-427f-b43d-39f5ae7a2b84",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                scenarioVersionId: 13,
                type: "COMMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                ],
                activities: {
                    displayableName: "Comment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment"],
                    type: "COMMENT_ADDED",
                },
                additionalFields: [],
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "2",
                    },
                    lastModifiedAt: "2024-10-02T08:48:42.599853Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-10-02T08:48:42.599853Z",
                id: "c03cae2e-95e6-44ac-8d5d-6d253a8f669a",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                scenarioVersionId: 13,
                type: "COMMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                ],
                activities: {
                    displayableName: "Comment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment"],
                    type: "COMMENT_ADDED",
                },
                additionalFields: [],
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "1",
                    },
                    lastModifiedAt: "2024-10-02T08:48:39.822978Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-10-02T08:48:39.822978Z",
                id: "c18a2e19-7a70-4150-bb12-eff61d21a2ed",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                scenarioVersionId: 13,
                type: "COMMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                ],
                activities: {
                    displayableName: "Comment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment"],
                    type: "COMMENT_ADDED",
                },
                additionalFields: [],
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "34",
                    },
                    lastModifiedAt: "2024-10-02T08:41:02.637105Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-10-02T08:41:02.637105Z",
                id: "72ec0519-2b1e-4fa9-a589-ca41372f4b1d",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                scenarioVersionId: 13,
                type: "COMMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
            {
                actions: [
                    {
                        displayableName: "Delete",
                        icon: "/assets/states/error.svg",
                        id: "delete_comment",
                    },
                    {
                        displayableName: "Edit",
                        icon: "/assets/states/error.svg",
                        id: "edit_comment",
                    },
                ],
                activities: {
                    displayableName: "Comment",
                    icon: "/assets/states/success.svg",
                    supportedActions: ["delete_comment", "edit_comment"],
                    type: "COMMENT_ADDED",
                },
                additionalFields: [],
                comment: {
                    content: {
                        status: "AVAILABLE",
                        value: "test",
                    },
                    lastModifiedAt: "2024-10-02T07:52:57.294963Z",
                    lastModifiedBy: "admin",
                },
                date: "2024-10-02T07:52:57.294963Z",
                id: "0a309251-9b98-4712-9d71-d5f31f0dd218",
                isActiveFound: false,
                isFound: false,
                isHidden: true,
                scenarioVersionId: 13,
                type: "COMMENT_ADDED",
                uiType: "item",
                user: "admin",
            },
            {
                isClicked: false,
                sameItemOccurrence: 5,
                uiType: "toggleItemsButton",
            },
        ];

        expect(extendActivitiesWithUIData(activitiesDataWithMetadata)).toMatchObject(expected);
    });
});
