/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.touk.nussknacker.engine.avro.schema;
@org.apache.avro.specific.AvroGenerated
public enum SampleStatus implements org.apache.avro.generic.GenericEnumSymbol<SampleStatus> {
  OK, ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SampleStatus\",\"namespace\":\"pl.touk.nussknacker.engine.avro.schema\",\"symbols\":[\"OK\",\"ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
