# In local development this config is annoying because it force to provide a deployment comment during every deployment
deploymentCommentSettings: {
  validationPattern: "(.*)"
  exampleComment: "issues/1234"
}
testCasesSettings {
  multipleEnabled: true
}
