name: Benchmarks E2E
on:
  schedule:
    - cron: '0 23 * * *'
jobs:
  benchmarks:
    name: Benchmarks E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "openjdk@1.11"
      - name: Run benchmarks
        run: |
          bash -c "export NUSSKNACKER_SCALA_VERSION=2.12 && sbt \"benchmarks/test:runMain pl.touk.nussknacker.engine.benchmarks.e2e.FlinkSteamingScenarioBenchmark 10000000\""
      - name: Store benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-e2e.csv
          path: tmp/benchmarkResult.csv
