name: Benchmarks JMH
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  benchmarks:
    name: Benchmarks JMH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.11.0.17
      - uses: sbt/setup-sbt@v1
      - name: Run benchmarks
        run: sbt "benchmarks/jmh:run -i 8 -wi 3 -f1 -t1 -rf csv"
      - name: Store benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: jmh-result.csv
          path: benchmarks/jmh-result.csv
