name: Release
on:
  workflow_dispatch:
    inputs:
      test:
        description: "Released Nussknacker version"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Output variables"
        run: |
          df -ah
          ls /opt/microsoft
          du -ah --max-depth 1 /opt/microsoft
          ls /usr/local
          du -ah --max-depth 1 /usr/local
          ls /usr/local/lib
          du -ah --max-depth 1 /usr/local/lib
          ls /opt/google
          du -ah --max-depth 1 /opt/google
          ls /opt
          du -ah --max-depth 1 /opt
          ls /usr/lib
          du -ah --max-depth 1 /usr/lib
          ls "$AGENT_TOOLSDIRECTORY"
          du -ah --max-depth 1 "$AGENT_TOOLSDIRECTORY"
          ls /opt/hostedtoolcache
          du -ah --max-depth 1 /opt/hostedtoolcache
