name: "Sync installation example"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - staging
      - demo
      - preview/*
      - release/*

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nu repository
        uses: actions/checkout@v3

      - name: Push folder to another repository
        env:
          NU_INSTALLATION_EXAMPLE_ACCESS_TOKEN: ${{ secrets.NU_INSTALLATION_EXAMPLE_PAT }}
          NUSSKNACKER_VERSION: "1.15.0"
        run: |
          ./.github/workflows/scripts/publishNuInstallationExample.sh
